version: "2"
services:
#-------------------------------------

  db:
    build:
      context: postgres
    volumes:
      - ./postgres:/usr/local/app/
      - fastapi-postgres-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: pgress

#-------------------------------------
  angular:
    build:
      context: angular
    volumes:
      - ./angular:/usr/src/app/
    ports:
      - "4200:4200"
    entrypoint:
      - /bin/sh 
      - /usr/src/app/pdata/startup.sh

#-------------------------------------

  python:
    build:
      context: python
    volumes:
      - ./python:/usr/src/app/
    ports:
      - "8000:8000"
    entrypoint: 
      - /bin/sh
      - /usr/src/app/pdata/startup.sh
    depends_on: 
      - db 


#-------------------------------------

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  fastapi-postgres-db: 
    external : yes    
  